---
- hosts: all
  roles:
    - common
    - { role: hw, when: facter_is_virtual == "false" }
    - { role: monitoring-client, when: "'monitoring' not in {{ group_names }}" }
    - { role: postfix-satellite, when: "'mailserver' not in {{ group_names }}" }
