- name: Install common hypervisor software
  apt: name={{ item }} state=present
  with_items:
    - lvm2
    - gdisk
    - bridge-utils
    - parted
    - qemu-kvm
    - seabios
    - vgabios
    - libvirt-bin
    - libvirt-doc
