- name: Install postfix
  apt: name=postfix state=present

- name: Configure postfix main.cf
  lineinfile: dest=/etc/postfix/main.cf state=present regexp="{{ item.regex }}" line="{{ item.line }}"
  with_items:
    - { regex: "^.*myhostname.*$", line: "myhostname = {{ ansible_nodename }}" }
    - { regex: "^.*mydestination.*", line: "mydestination = {{ ansible_nodename }},localhost.{{ facter_domain }},localhost" }
    - { regex: "^.*relayhost.*", line: "relayhost = {{ postfix_relay_host }}"}
    - { regex: "^.*mynetworks.*", line: "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128" }
    - { regex: "^.*inet_interfaces.*", line: "inet_interfaces = loopback-only" }
    - { regex: "^.*inet_protocols.*", line: "inet_protocols = all" }
  notify:
    - restart postfix

- name: Set mailname
  copy: dest=/etc/mailname content={{ ansible_nodename }} owner=root group=root mode=0644
  notify:
    - restart postfix

- name: set root alias
  lineinfile: 'dest=/etc/aliases regexp="^root:" line="root: {{ root_recipient }}"'
  notify:
    - newaliases
