- name: Install workstation software
  apt: name={{ item }} state=present
  with_items:
    - conky-all
    - vlc
    - terminology
    - curl
    - xfce4-sensors-plugin
    - xfce4-goodies
    - xsensors
    - lm-sensors
    - nfs-common
    - openjdk-8-jre
    - meld
    - p7zip-full
    - unrar
    - gnupg2
