- name: Install workstation software
  apt: name={{ item }} state=present
  with_items:
    - conky-all
    - curl
    - fslint
    - gnupg2
    - i3lock
    - lm-sensors
    - meld
    - ncdu
    - nfs-common
    - openjdk-8-jre
    - p7zip-full
    - python-dev
    - terminology
    - unrar
    - vagrant
    - virtualbox
    - virtualenv
    - vlc
    - xautolock
    - xfce4-goodies
    - xfce4-sensors-plugin
    - xsensors


- name: Remove harmful / unneeded
  apt: name={{ item }} state=absent
  with_items:
    - xscreensaver
