- name: Add Yubico Repository Key
  apt_key:
    keyserver: keyserver.ubuntu.com 
    id: '0x32CBA1A9'
    state: present 

- name: Add Yubico Repository (>=2.1)
  apt_repository: 
    repo: 'deb http://ppa.launchpad.net/yubico/stable/ubuntu xenial main'
    filename: terminology.list
    update_cache: yes
    state: present
  when: (ansible_version.major >= 2 and ansible_version.minor >= 1)

- name: Add Yubico Repository (<=2.1)
  apt_repository: 
    repo: 'deb http://ppa.launchpad.net/yubico/stable/ubuntu xenial main'
    update_cache: yes
    state: present
  when: (ansible_version.major == 2 and ansible_version.minor < 1) or
        (ansible_version.major < 2 )

- name: Install yubioath 
  apt: name=yubioath-desktop state=present
