- name: Install security software
  apt: name={{ item }} state=present
  with_items:
    - ebtables
    - openssh-blacklist
    - openssh-blacklist-extra

- name: No Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^PermitRootLogin'
    line='PermitRootLogin {{ sshd_permit_root_login}}'
  notify:
    - restart ssh

# Include other Tasks

- include: rkhunter.yml
- include: fail2ban.yml
