- name: Install unattended-upgrades software
  apt: name=unattended-upgrades state=present
- name: Add unattended-upgrades config
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=0644
