- name: Install tor software
  apt: name=tor state=present
  
- name: Configure TOR
  lineinfile: 
    dest: '/etc/tor/torrc' 
    regexp: '{{ item.regexp }}' 
    line: '{{ item.line }}'
    state: '{{ item.state }}'
  with_items: '{{ tor_options }}'
