- name: Create directories
  file: path={{ NAS_mountpoint }}/{{ item }} state=directory
  with_items: "{{ NAS_shares }}"

- name: Set mountpoints
  mount: name={{ NAS_mountpoint }}/{{ item }} src={{NAS_host }}:{{ item }} fstype=nfs opts={{ NAS_options }} state={{ NAS_state }}
  with_items: "{{ NAS_shares }}"
