#!/bin/bash

die() {
    if [[ -n "$TEMPDIR" ]] ; then
        umount $TEMPDIR >/dev/null 2>&1
        rm -r $TEMPDIR >/dev/null 2>&1
    fi
    echo $1;
    exit 1
}

if [[ -z "$2" ]]; then
    echo "Need owner"
    exit 99
fi

DEVICE=$1
OWNER=$2
TEMPDIR=$(mktemp -d)

mkfs.ext4 -q $DEVICE || die "could not create Filesystem in $DEVICE"
mount $DEVICE $TEMPDIR || die "could not mount $DEVICE"
chown $OWNER $TEMPDIR || die "could not chown $DEVICE to $OWNER"
sync
umount $TEMPDIR || die "Could not unmount $TEMPDIR"
rm -r $TEMPDIR || die "could not delete $TEMPDIR"